### ISSUE TITLE
"docker run -v /<full_path>/... " fails

### ISSUE THREAD

**Issue by kozo2** [Bioconductor/bioconductor.org#81]
Build using Docker fails as below.
Please let me know if you have any ideas for solving this.

```
cd ~
git clone https://github.com/Bioconductor/bioconductor.org
docker run -v /home/kozo2/bioconductor.org:/bioconductor.org/ -p 3000:3000 bioconductor/website:latest
```
```
copying bioc_views.html to content/packages/3.12/BiocViews.html
copying bioc_views.html to content/packages/3.13/BiocViews.html
Loading site… done
kramdown warning(s) for <Nanoc::CompilationItemRepView item.identifier=/developers/how-to/git/new-package-workflow/ name=default>
  No link definition for link ID '1' found on line 7
kramdown warning(s) for <Nanoc::CompilationItemRepView item.identifier=/developers/how-to/troubleshoot-build-report/ name=default>
  No link definition for link ID 'example [biobase](https://bioconductor.org/packages/release/bioc/html/biobase.html)' found on line 16
#<Thread:0x0000561e42d988c8@/usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/compiler/phases/write.rb:14 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/2.6.0/fileutils.rb:1386:in `initialize': No such file or directory @ rb_sysopen - output/style/style.css (#<Thread:0x0000561e42d9aa88@/usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/compiler/phases/write.rb:14 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/2.6.0/fileutils.rb:1386:in `initialize': kramdown warning(s) for <Nanoc::CompilationItemRepView item.identifier=/news/bioc_3_9_release/ name=default>
  No link definition for link ID 'fl' found on line 2781
  No link definition for link ID 'flwy' found on line 2781
  No link definition for link ID 'from @vlakam' found on line 4658
Errno::ENOENTNo such file or directory @ rb_sysopen - output/about/removed-packages/index.html)  No link definition for link ID 'msdata::spectrum::getmzintensitypairs()' found on line 6041
  No link definition for link ID 'a-z' found on line 6957
  No link definition for link ID '5' found on line 7238
  No link definition for link ID 'i' found on line 7722
  Found no end tag for 'NON_REF' (line 7975) - auto-closing it
  No link definition for link ID '2019-03-27' found on line 8476
  No link definition for link ID '2019-01-04' found on line 8492
#<Thread:0x0000561e42d99e30@/usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/compiler/phases/write.rb:14 run> terminated with exception (report_on_exception is true):
 (
Errno::ENOENT)
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1386:in `open'
  No link definition for link ID '2018-12-07' found on line 8498
  No link definition for link ID '2018-12-07' found on line 8501
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1386:in `open'
  No link definition for link ID '2018-12-07' found on line 8502
  No link definition for link ID '2018-12-07' found on line 8504
  No link definition for link ID '2018-11-07' found on line 8510
/usr/local/lib/ruby/2.6.0/fileutils.rb:1386:in `initialize': No such file or directory @ rb_sysopen - output/about/scientific-advisory-board/index.html (Errno::ENOENT)      from /usr/local/lib/ruby/2.6.0/fileutils.rb:1386:in `block in copy_file'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1385:in `open'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1385:in `copy_file'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:492:in `copy_file'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:419:in `block in cp'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1557:in `block in fu_each_src_dest'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1573:in `fu_each_src_dest0'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:418:in `cp'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:51:in `write_single'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:18:in `block in write'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:17:in `each'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:17:in `write'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:12:in `block in write_all'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:11:in `each'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:11:in `write_all'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/compiler/phases/write.rb:21:in `block in start'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1386:in `block in copy_file'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1385:in `open'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1385:in `copy_file'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:492:in `copy_file'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:419:in `block in cp'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1557:in `block in fu_each_src_dest'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1573:in `fu_each_src_dest0'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:418:in `cp'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:51:in `write_single'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:18:in `block in write'

        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1386:in `open'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1386:in `block in copy_file'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1385:in `open'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1385:in `copy_file'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:17:in `each'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:17:in `write'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:12:in `block in write_all'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:11:in `each'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:11:in `write_all'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:492:in `copy_file'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/compiler/phases/write.rb:21:in `block in start'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:419:in `block in cp'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1557:in `block in fu_each_src_dest'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1573:in `fu_each_src_dest0'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
        from /usr/local/lib/ruby/2.6.0/fileutils.rb:418:in `cp'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:51:in `write_single'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:18:in `block in write'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:17:in `each'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:17:in `write'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:12:in `block in write_all'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:11:in `each'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/item_rep_writer.rb:11:in `write_all'
        from /usr/local/bundle/gems/nanoc-4.9.0/lib/nanoc/base/services/compiler/phases/write.rb:21:in `block in start'

Captain! We’ve been hit!

Errno::ENOENT: No such file or directory @ rb_sysopen - output/style/style.css

  0. /usr/local/lib/ruby/2.6.0/fileutils.rb:1386:in `initialize'
  1. /usr/local/lib/ruby/2.6.0/fileutils.rb:1386:in `open'
  2. /usr/local/lib/ruby/2.6.0/fileutils.rb:1386:in `block in copy_file'
  3. /usr/local/lib/ruby/2.6.0/fileutils.rb:1385:in `open'
  4. /usr/local/lib/ruby/2.6.0/fileutils.rb:1385:in `copy_file'
  5. /usr/local/lib/ruby/2.6.0/fileutils.rb:492:in `copy_file'
  6. /usr/local/lib/ruby/2.6.0/fileutils.rb:419:in `block in cp'
  7. /usr/local/lib/ruby/2.6.0/fileutils.rb:1557:in `block in fu_each_src_dest'
  8. /usr/local/lib/ruby/2.6.0/fileutils.rb:1573:in `fu_each_src_dest0'
  9. /usr/local/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
  ... 9 lines omitted (see crash.log for details)

A detailed crash log has been written to ./crash.log.
```

**Comment by kozo2** [comment]
Sorry, I found that the cause of the problem was that I was running the Docker command from Ubuntu on WSL2. When I run the Docker command from a non-WSL2-Ubuntu, I can see the website without any problems.
